//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPessoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        public int idpessoa { get; set; }
        public string nome { get; set; }
        public long cpf { get; set; }
        public decimal renda { get; set; }
    }
}
